### ISSUE TITLE
Error with invoke

### ISSUE THREAD

**Issue by thednp** [atilafassina/quantum#10]
Hi Atttila o/

I installed all good, however click listener throws this

```
core.js:117 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'invoke')
    at invoke (core.js:117:39)
    at greet (App.tsx:9:23)
    at HTMLFormElement.<anonymous> (App.tsx:51:11)
```

[✘] Environment
    - OS: Arch Linux 20230709.0.163418 X64
    ✘ webkit2gtk-4.1: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rsvg2: 2.56.2
    ✘ rustc: not installed!
      Maybe you don't have rust installed! Visit https://rustup.rs/
    ✘ Cargo: not installed!
      Maybe you don't have rust installed! Visit https://rustup.rs/
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 20.10.0
    - pnpm: 9.1.4
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta (no lockfile)
    - tauri-build [RUST]: no manifest (no lockfile)
    - wry [RUST]: no manifest (no lockfile)
    - tao [RUST]: no manifest (no lockfile)
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS

I guess I have to go through presequisites.

**Comment by atilafassina** [comment]
😅 you actually got quite far without Rust. I'm impressed! haha

Current Quantum is actually on Tauri v2, so probably this is the best link for you: [Tauri v2: Prerequisites](https://v2.tauri.app/start/prerequisites/)
