### ISSUE TITLE
Task to bump release automatically.

### ISSUE THREAD

**Issue by atilafassina** [atilafassina/quantum#13]
To keep all 3 `version` declarations in sync, it's best to have a version bumping script and thus also pushing Notes / Changelog to CrabNebula.

- [ ] Updates `Cargo.toml` version.

~~- [ ] Updates `package.json` version.~~
~~- [ ] Updates `tauri.conf.json` version.~~

**Comment by Brendonovich** [comment]
I don't think this is necessary, `package.json` can go without a `version` and the Tauri CLI can lookup the version from `Cargo.toml` if `tauri.conf.json` doesn't have one. In MacroGraph I just bump `Cargo.toml` and [a workflow](https://github.com/Brendonovich/macrograph/blob/86c5e725cbb4c433318c4516f48126e6b9528e8b/.github/workflows/release-desktop.yaml#L19-L41) reads the version number from there, creates a tag, a release, etc.

**Comment by atilafassina** [comment]
> I don't think this is necessary, `package.json` can go without a `version` and the Tauri CLI can lookup the version from `Cargo.toml` if `tauri.conf.json` doesn't have one. In MacroGraph I just bump `Cargo.toml` and [a workflow](https://github.com/Brendonovich/macrograph/blob/86c5e725cbb4c433318c4516f48126e6b9528e8b/.github/workflows/release-desktop.yaml#L19-L41) reads the version number from there, creates a tag, a release, etc.

ohhh, absolutely! I will borrow that!

![it's ours now](https://github.com/atilafassina/quantum/assets/2382552/29283311-95d9-43cd-9af6-a8f965da8eab)
